import { Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "english",
    name: "General English",
    description: "Grammar, Vocabulary, Comprehension, and Sentence Structure",
    topics: [
      { id: "comprehension", name: "Comprehension", description: "Reading and Analysis" },
      { id: "editing-proofreading", name: "Editing / Proof Reading", description: "Sentence Correction" },
      { id: "rearranging-sentences", name: "Rearranging of Jumbled Sentences", description: "Sentence Ordering" },
      { id: "narration", name: "Narration", description: "Direct and Indirect Speech" },
      { id: "modals", name: "Modals", description: "Can, Could, May, Might, etc." },
      { id: "articles", name: "Articles", description: "A, An, The" },
      { id: "phrases-pronouns", name: "Phrases & Pronouns", description: "Usage and Identification" },
      { id: "homonyms-homophones", name: "Homonyms/Homophones", description: "Similar Sounding Words" },
      { id: "clauses", name: "Clauses", description: "Types and Usage" },
      { id: "punctuation", name: "Punctuation", description: "Correct Usage of Marks" },
      { id: "synonyms-antonyms", name: "Synonyms & Antonyms", description: "Vocabulary Building" },
      { id: "idioms-phrases", name: "Idioms & Phrases", description: "Common Expressions" },
      { id: "prepositions", name: "Uses of Prepositions", description: "In, On, At, etc." },
      { id: "active-passive", name: "Active & Passive Voice", description: "Voice Transformation" },
    ],
  },
  {
    id: "jk-gk",
    name: "General Awareness & J&K UT",
    description: "Current Affairs, Indian History/Geography, and J&K Specific Knowledge",
    topics: [
      { id: "current-events", name: "Current Events", description: "National & International Importance" },
      { id: "india-divisions", name: "Political & Physical Divisions of India", description: "Geography of India" },
      { id: "indian-culture-struggle", name: "Indian Culture & Freedom Struggle", description: "History and Heritage" },
      { id: "demography-census", name: "Demography & Census", description: "Features and Functions" },
      { id: "rivers-lakes-india", name: "Important Rivers & Lakes in India", description: "Indian Hydrography" },
      { id: "weather-transport-india", name: "Weather, Climate & Transport", description: "Indian Climate and Logistics" },
      { id: "jk-history", name: "J&K History", description: "Historical Events of J&K" },
      { id: "jk-economy", name: "J&K Economy", description: "Economic Aspects of J&K" },
      { id: "jk-geography", name: "J&K Geography", description: "Climate, Crops, Rivers, Flora & Fauna" },
      { id: "jk-heritage-culture", name: "J&K Heritage & Culture", description: "Traditions and Arts" },
      { id: "jk-tourist-destinations", name: "J&K Tourist Destinations", description: "Important Places to Visit" },
    ],
  },
  {
    id: "math",
    name: "Numerical Ability",
    description: "Basic Arithmetic and Quantitative Aptitude",
    topics: [
      { id: "number-system", name: "Number System", description: "Basics and Operations" },
      { id: "percentage", name: "Percentage", description: "Calculations and Applications" },
      { id: "average", name: "Average", description: "Mean and Related Concepts" },
      { id: "profit-loss", name: "Profit & Loss", description: "Business Mathematics" },
      { id: "ratio-proportion", name: "Ratio & Proportion", description: "Comparisons and Scales" },
      { id: "time-work", name: "Time & Work", description: "Efficiency and Duration" },
      { id: "speed-distance-time", name: "Speed, Distance and Time", description: "Motion Problems" },
    ],
  },
  {
    id: "reasoning",
    name: "Reasoning Ability",
    description: "Verbal and Logical Reasoning",
    topics: [
      { id: "number-series", name: "Number Series", description: "Pattern Identification" },
      { id: "letter-series", name: "Letter Series", description: "Alphabetical Patterns" },
      { id: "coding-decoding", name: "Coding Decoding", description: "Ciphering and Deciphering" },
      { id: "direction-sense", name: "Direction Sense", description: "Spatial Awareness" },
      { id: "blood-relations", name: "Blood Relations", description: "Family Tree Problems" },
      { id: "mathematical-reasoning", name: "Mathematical Reasoning", description: "Logic in Math" },
      { id: "statements-conclusions", name: "Statements & Conclusions", description: "Logical Deductions" },
    ],
  },
  {
    id: "computer",
    name: "Basic Concepts of Computers",
    description: "Fundamentals, Hardware, Software, and Internet",
    topics: [
      { id: "computer-fundamentals", name: "Fundamentals of Computer Sciences", description: "Basics and History" },
      { id: "hardware-software", name: "Hardware & Software", description: "Components and Programs" },
      { id: "input-output-devices", name: "Input & Output Devices", description: "Peripherals" },
      { id: "operating-system", name: "Operating System", description: "Windows, Linux, etc." },
      { id: "ms-office", name: "MS Office Suite", description: "Word, Excel, Access, PowerPoint" },
      { id: "email-internet", name: "E-mail & Internet", description: "Web and Communication" },
    ],
  },
];
